                            SALES PERFORMANCE REPORT

                                 Including GST

                        Avg and % calculated on Retail $

 

_________________________________________________________________________________________

Sales Person   Retail $   Discount    Returns      Net $   Avg Sale   Avg Sale    % Store

              Incl Disc                                       Units          $      Total

_________________________________________________________________________________________

Alejandra        134.99       0.00    -134.99       0.00       1.00     134.99      0.00%

Alice            231.98     -50.00    -381.97    -149.99       0.67      77.33      0.01%

Amal             381.97     -26.00    -237.98     143.99       1.50     190.99      0.01%

Amanda        57,239.91  10,199.23  -3,265.24  53,974.67       1.67     173.98      1.72%

Amy              143.99    -102.00    -297.98    -153.99       0.50      72.00      0.00%

Amy               95.98     -24.00     -95.98       0.00       2.00      95.98      0.00%

Andy             399.97      39.00       0.00     399.97       1.33     133.32      0.01%

Angela             0.00     -48.00    -111.99    -111.99       0.00       0.00      0.00%

Anita              0.00     -17.00    -152.99    -152.99       0.00       0.00      0.00%

Anna             129.00     -25.00    -224.99     -95.99       1.00     129.00      0.00%

Anthony        3,495.94     300.90     -54.00   3,441.94       1.25     174.80      0.11%

Avishka       19,354.29   5,200.20  -1,034.73  18,319.56       1.35     154.83      0.58%

Bansi          2,635.81     506.99    -332.98   2,302.83       1.43     188.27      0.08%

Barbara       69,056.24  17,139.75  -6,263.99  62,792.25       1.57     168.84      2.08%

Barclay          152.99       4.00    -116.99      36.00       1.00     152.99      0.00%

Bronte           859.93     160.00       0.00     859.93       2.00     214.98      0.03%

Carla            295.99       0.00    -295.99       0.00       1.00     295.99      0.01%

Carol             62.99      27.00       0.00      62.99       1.00      62.99      0.00%

Catherine      5,723.64     562.93  -1,277.92   4,445.72       1.52     197.37      0.17%

Charlotte          0.00       0.00     -99.00     -99.00       0.00       0.00      0.00%

Christian        451.95     -86.00    -587.94    -135.99       1.25     112.99      0.01%

Christian      8,926.77   3,025.29    -917.90   8,008.87       1.73     162.30      0.27%

Christine        313.48    -155.00  -1,632.41  -1,318.93       0.18      28.50      0.01%

Cindy             71.99     -63.00    -476.98    -404.99       0.50      36.00      0.00%

Cindy            528.46    -265.50  -2,432.84  -1,904.38       0.36      37.75      0.02%

Clair            791.92     228.00       0.00     791.92       8.00     791.92      0.02%

Claire           143.99       0.00    -143.99       0.00       1.00     143.99      0.00%

DAVID JONES      188.19      30.80    -159.99      28.20       2.00     188.19      0.01%

David          5,211.69     838.94    -305.97   4,905.72       1.56     193.03      0.16%

Daya             195.49      51.49    -146.99      48.50       1.50      97.75      0.01%

Debbie             0.00     -50.99     -99.00     -99.00       0.00       0.00      0.00%

Dhanushree       395.97       9.20    -214.19     181.78       3.00     395.97      0.01%

Diana          3,170.93     661.99    -692.17   2,478.76       1.45     158.55      0.10%

Dolly          1,129.92      76.00       0.00   1,129.92       6.00     564.96      0.03%

Elena              0.00       0.00    -129.99    -129.99       0.00       0.00      0.00%

Emanuele      19,489.46   3,944.80  -1,331.89  18,157.57       1.67     158.45      0.59%

Emily          3,313.23     321.50     -89.99   3,223.24       1.80     220.88      0.10%

Erika              0.00       0.00    -149.00    -149.00       0.00       0.00      0.00%

Farnaz           323.96       0.00    -323.96       0.00       4.00     323.96      0.01%

Fatemeh        4,740.65   1,019.00       0.00   4,740.65       1.46     197.53      0.14%

Florencia          0.00       0.00     -49.00     -49.00       0.00       0.00      0.00%

Francesca     45,504.31   8,773.16  -3,656.77  41,847.54       1.76     207.78      1.37%

Gabrielle      1,671.89     356.98       0.00   1,671.89       1.40     167.19      0.05%

Gail             259.99      19.00    -278.99     -19.00       2.00     259.99      0.01%

Gearldine          0.00     -60.50    -284.50    -284.50       0.00       0.00      0.00%

Georgia      149,964.25  29,098.32  -8,426.03 141,538.22       1.72     187.93      4.52%

Gina             159.00     -14.01    -203.99     -44.99       0.50      79.50      0.00%

Giovanna         369.97     -16.00    -423.96     -53.99       0.75      92.49      0.01%

Grace              0.00       0.00     -79.00     -79.00       0.00       0.00      0.00%

Haniya             0.00     -29.80    -119.20    -119.20       0.00       0.00      0.00%

India          7,070.03   1,703.27     -71.99   6,998.04       1.63     130.93      0.21%

Ingrid            59.99       0.00     -59.99       0.00       1.00      59.99      0.00%

Isabel Dias       89.99       0.00     -89.99       0.00       1.00      89.99      0.00%

Jacqueline       116.99       0.00    -116.99       0.00       1.00     116.99      0.00%

Jennifer         178.99    -230.80    -987.14    -808.15       0.25      22.37      0.01%

Jessica            0.00     -19.80     -79.20     -79.20       0.00       0.00      0.00%

Jessie        59,650.25  11,849.76  -2,494.88  57,155.37       1.64     212.28      1.80%

Jill (Jilly) 141,761.53  32,536.08  -9,254.16 132,507.37       1.70     203.68      4.27%

Jiyaa              0.00     -30.00    -119.99    -119.99       0.00       0.00      0.00%

Julie            451.45     -67.00    -592.45    -141.00       1.20      90.29      0.01%

Kandy              0.00     -52.00    -207.98    -207.98       0.00       0.00      0.00%

Katerina         193.48    -150.68    -479.27    -285.79       0.40      38.70      0.01%

Kelly             97.99    -152.00    -467.96    -369.97       0.33      32.66      0.00%

Kiara              0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Klara            360.97     -64.00    -360.97       0.00       1.00     120.32      0.01%

Lana               0.00    -129.50    -770.45    -770.45       0.00       0.00      0.00%

Lara             279.98       0.00    -279.98       0.00       1.00     139.99      0.01%

Lea                0.00     -60.79    -228.19    -228.19       0.00       0.00      0.00%

Leah             415.18     -67.20    -398.98      16.20       3.00     415.18      0.01%

Lesley             0.00     -10.00     -89.99     -89.99       0.00       0.00      0.00%

Lily               0.00      -8.00     -71.99     -71.99       0.00       0.00      0.00%

Linda              0.00     -14.00    -125.99    -125.99       0.00       0.00      0.00%

Louise            95.99      -9.00    -355.97    -259.98       0.33      32.00      0.00%

Louise             0.00     -28.00    -111.99    -111.99       0.00       0.00      0.00%

Loustos            0.00     -12.00    -107.99    -107.99       0.00       0.00      0.00%

Margaret         161.99       0.00    -161.99       0.00       1.00     161.99      0.00%

Margaux           83.99     -56.00     -83.99       0.00       1.00      83.99      0.00%

Maria        441,049.27 101,387.66 -35,488.04 405,561.23       1.66     167.00     13.29%

Maria             63.99       4.00     -47.99      16.00       1.00      63.99      0.00%

Maria Eduard       0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Marilyn          160.99     -13.00    -157.99       3.00       1.50      80.50      0.00%

Marina             0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Mark           1,384.88     187.00  -1,047.92     336.96       1.75     173.11      0.04%

Marta            269.99     109.98       0.00     269.99       3.00     269.99      0.01%

Martha Lucia   1,613.29     146.10    -281.48   1,331.81       1.44     179.25      0.05%

Matias        23,130.87   4,779.01  -1,327.87  21,803.00       1.56     136.87      0.70%

Meg                0.00     -13.00    -116.99    -116.99       0.00       0.00      0.00%

Merrilyn     120,163.06  19,516.73  -7,570.47 112,592.59       1.49     155.65      3.62%

Michael            0.00     -10.00     -89.99     -89.99       0.00       0.00      0.00%

Miryana          135.99      34.00       0.00     135.99       1.00     135.99      0.00%

Mobina           251.48      12.50    -173.99      77.49       1.50     125.74      0.01%

Nenci            424.98     -26.99    -817.96    -392.98       0.57      60.71      0.01%

Nenci              0.00     -37.00    -332.99    -332.99       0.00       0.00      0.00%

Nguyen Mai A       0.00     -40.99     -89.00     -89.00       0.00       0.00      0.00%

Nicole            39.20     -50.19    -208.99    -169.79       0.33      13.07      0.00%

Nikki              0.00     -49.75    -149.25    -149.25       0.00       0.00      0.00%

Pamela           897.47    -249.30  -2,023.62  -1,126.15       0.33      99.72      0.03%

Pammi        182,375.21  35,249.46 -12,309.30 170,065.91       1.60     168.09      5.49%

Paul              99.99     100.00       0.00      99.99       1.00      99.99      0.00%

Paula        369,605.51  68,789.40 -20,502.28 349,103.23       1.60     180.38     11.13%

Pilar          2,375.13     318.93    -498.20   1,876.93       1.25     148.45      0.07%

Rabeya             0.00     -13.00    -116.99    -116.99       0.00       0.00      0.00%

Rabina         3,249.78     706.94    -797.96   2,451.82       1.46     116.06      0.10%

Raquel         2,630.18     142.31  -1,110.16   1,520.02       1.21     109.59      0.08%

Renee        599,842.87 137,123.27 -39,668.23 560,174.64       1.68     170.94     18.07%

Renne             89.99       0.00     -89.99       0.00       1.00      89.99      0.00%

Rhonda           772.48      76.97    -609.46     163.02       1.40     154.50      0.02%

Rimma            845.14    -116.20  -1,538.90    -693.76       0.70      84.51      0.03%

Ruchika            0.00     -40.00    -159.99    -159.99       0.00       0.00      0.00%

Saakshi           90.30       0.00     -90.30       0.00       1.00      90.30      0.00%

Sally            359.99      -8.00    -431.98     -71.99       0.50     180.00      0.01%

Sandra           134.99       0.00    -134.99       0.00       1.00     134.99      0.00%

Sara          20,634.21   3,634.50  -1,908.36  18,725.85       1.53     139.42      0.62%

Sarah          2,416.88     292.98       0.00   2,416.88       3.50     604.22      0.07%

Sarah         75,490.86  17,559.65  -5,785.76  69,705.10       1.58     185.03      2.27%

Saraya           126.19      22.80    -139.99     -13.80       2.00     126.19      0.00%

Shabair      310,456.73  57,998.99 -17,615.12 292,841.61       1.68     186.01      9.35%

Shanley            0.00     -35.00    -314.99    -314.99       0.00       0.00      0.00%

Shann            279.19      29.80    -159.99     119.20       2.00     279.19      0.01%

Shirley            0.00     -27.00     -62.99     -62.99       0.00       0.00      0.00%

Shonnah           63.20       6.80     -80.99     -17.79       1.00      63.20      0.00%

Sofia          1,252.74     223.40     -79.20   1,173.54       1.11     139.19      0.04%

Sophia             0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Store            720.37     -10.39  -1,451.93    -731.56       0.58      60.03      0.02%

Susan              0.00      -9.00     -80.99     -80.99       0.00       0.00      0.00%

Susan         38,878.88   8,400.57  -2,407.46  36,471.42       1.60     190.58      1.17%

Susan            103.99     -26.00    -103.99       0.00       1.00     103.99      0.00%

Susan            597.98      59.98       0.00     597.98       1.50     149.50      0.02%

Susanne            0.00     -15.00    -134.99    -134.99       0.00       0.00      0.00%

Susie             80.99       0.00     -80.99       0.00       1.00      80.99      0.00%

Tania              0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Tania              0.00     -70.99     -99.00     -99.00       0.00       0.00      0.00%

Tara               0.00     -75.00    -224.98    -224.98       0.00       0.00      0.00%

Tate          33,381.38   7,402.21  -2,256.21  31,125.17       1.74     171.19      1.01%

Taznin             0.00     -26.00    -103.99    -103.99       0.00       0.00      0.00%

Teresa       415,018.33  95,771.59 -24,986.88 390,031.45       1.63     166.07     12.50%

Tina               0.00     -55.00    -294.98    -294.98       0.00       0.00      0.00%

Tracey        27,901.65   7,633.29  -1,632.38  26,269.27       1.65     156.75      0.84%

Valeria            0.00       0.00    -189.00    -189.00       0.00       0.00      0.00%

Victoria       2,407.32     904.42     -74.99   2,332.33       1.93     160.49      0.07%

Wendy Ann     18,843.52   3,883.40    -829.43  18,014.09       1.45     138.56      0.57%

Yifan            127.49     -42.50    -127.49       0.00       1.00     127.49      0.00%

Zoe                0.00      -9.00     -80.99     -80.99       0.00       0.00      0.00%

_________________________________________________________________________________________

Total       3,319,620.7 697,760.35-245,878.093,073,742.6       1.63     172.50    100.00%

_________________________________________________________________________________________

Printed by Maria

At Store SC FS Balmain

9/02/2025 4:41 PM        POSREPS.SalesPerformance44251

In [ ]:
data = """
                            SALES PERFORMANCE REPORT

                                 Including GST

                        Avg and % calculated on Retail $

 

_________________________________________________________________________________________

Sales Person   Retail $   Discount    Returns      Net $   Avg Sale   Avg Sale    % Store

              Incl Disc                                       Units          $      Total

_________________________________________________________________________________________

Alejandra        134.99       0.00    -134.99       0.00       1.00     134.99      0.00%

Alice            231.98     -50.00    -381.97    -149.99       0.67      77.33      0.01%

Amal             381.97     -26.00    -237.98     143.99       1.50     190.99      0.01%

Amanda        57,239.91  10,199.23  -3,265.24  53,974.67       1.67     173.98      1.72%

Amy              143.99    -102.00    -297.98    -153.99       0.50      72.00      0.00%

Amy               95.98     -24.00     -95.98       0.00       2.00      95.98      0.00%

Andy             399.97      39.00       0.00     399.97       1.33     133.32      0.01%

Angela             0.00     -48.00    -111.99    -111.99       0.00       0.00      0.00%

Anita              0.00     -17.00    -152.99    -152.99       0.00       0.00      0.00%

Anna             129.00     -25.00    -224.99     -95.99       1.00     129.00      0.00%

Anthony        3,495.94     300.90     -54.00   3,441.94       1.25     174.80      0.11%

Avishka       19,354.29   5,200.20  -1,034.73  18,319.56       1.35     154.83      0.58%

Bansi          2,635.81     506.99    -332.98   2,302.83       1.43     188.27      0.08%

Barbara       69,056.24  17,139.75  -6,263.99  62,792.25       1.57     168.84      2.08%

Barclay          152.99       4.00    -116.99      36.00       1.00     152.99      0.00%

Bronte           859.93     160.00       0.00     859.93       2.00     214.98      0.03%

Carla            295.99       0.00    -295.99       0.00       1.00     295.99      0.01%

Carol             62.99      27.00       0.00      62.99       1.00      62.99      0.00%

Catherine      5,723.64     562.93  -1,277.92   4,445.72       1.52     197.37      0.17%

Charlotte          0.00       0.00     -99.00     -99.00       0.00       0.00      0.00%

Christian        451.95     -86.00    -587.94    -135.99       1.25     112.99      0.01%

Christian      8,926.77   3,025.29    -917.90   8,008.87       1.73     162.30      0.27%

Christine        313.48    -155.00  -1,632.41  -1,318.93       0.18      28.50      0.01%

Cindy             71.99     -63.00    -476.98    -404.99       0.50      36.00      0.00%

Cindy            528.46    -265.50  -2,432.84  -1,904.38       0.36      37.75      0.02%

Clair            791.92     228.00       0.00     791.92       8.00     791.92      0.02%

Claire           143.99       0.00    -143.99       0.00       1.00     143.99      0.00%

DAVID JONES      188.19      30.80    -159.99      28.20       2.00     188.19      0.01%

David          5,211.69     838.94    -305.97   4,905.72       1.56     193.03      0.16%

Daya             195.49      51.49    -146.99      48.50       1.50      97.75      0.01%

Debbie             0.00     -50.99     -99.00     -99.00       0.00       0.00      0.00%

Dhanushree       395.97       9.20    -214.19     181.78       3.00     395.97      0.01%

Diana          3,170.93     661.99    -692.17   2,478.76       1.45     158.55      0.10%

Dolly          1,129.92      76.00       0.00   1,129.92       6.00     564.96      0.03%

Elena              0.00       0.00    -129.99    -129.99       0.00       0.00      0.00%

Emanuele      19,489.46   3,944.80  -1,331.89  18,157.57       1.67     158.45      0.59%

Emily          3,313.23     321.50     -89.99   3,223.24       1.80     220.88      0.10%

Erika              0.00       0.00    -149.00    -149.00       0.00       0.00      0.00%

Farnaz           323.96       0.00    -323.96       0.00       4.00     323.96      0.01%

Fatemeh        4,740.65   1,019.00       0.00   4,740.65       1.46     197.53      0.14%

Florencia          0.00       0.00     -49.00     -49.00       0.00       0.00      0.00%

Francesca     45,504.31   8,773.16  -3,656.77  41,847.54       1.76     207.78      1.37%

Gabrielle      1,671.89     356.98       0.00   1,671.89       1.40     167.19      0.05%

Gail             259.99      19.00    -278.99     -19.00       2.00     259.99      0.01%

Gearldine          0.00     -60.50    -284.50    -284.50       0.00       0.00      0.00%

Georgia      149,964.25  29,098.32  -8,426.03 141,538.22       1.72     187.93      4.52%

Gina             159.00     -14.01    -203.99     -44.99       0.50      79.50      0.00%

Giovanna         369.97     -16.00    -423.96     -53.99       0.75      92.49      0.01%

Grace              0.00       0.00     -79.00     -79.00       0.00       0.00      0.00%

Haniya             0.00     -29.80    -119.20    -119.20       0.00       0.00      0.00%

India          7,070.03   1,703.27     -71.99   6,998.04       1.63     130.93      0.21%

Ingrid            59.99       0.00     -59.99       0.00       1.00      59.99      0.00%

Isabel Dias       89.99       0.00     -89.99       0.00       1.00      89.99      0.00%

Jacqueline       116.99       0.00    -116.99       0.00       1.00     116.99      0.00%

Jennifer         178.99    -230.80    -987.14    -808.15       0.25      22.37      0.01%

Jessica            0.00     -19.80     -79.20     -79.20       0.00       0.00      0.00%

Jessie        59,650.25  11,849.76  -2,494.88  57,155.37       1.64     212.28      1.80%

Jill (Jilly) 141,761.53  32,536.08  -9,254.16 132,507.37       1.70     203.68      4.27%

Jiyaa              0.00     -30.00    -119.99    -119.99       0.00       0.00      0.00%

Julie            451.45     -67.00    -592.45    -141.00       1.20      90.29      0.01%

Kandy              0.00     -52.00    -207.98    -207.98       0.00       0.00      0.00%

Katerina         193.48    -150.68    -479.27    -285.79       0.40      38.70      0.01%

Kelly             97.99    -152.00    -467.96    -369.97       0.33      32.66      0.00%

Kiara              0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Klara            360.97     -64.00    -360.97       0.00       1.00     120.32      0.01%

Lana               0.00    -129.50    -770.45    -770.45       0.00       0.00      0.00%

Lara             279.98       0.00    -279.98       0.00       1.00     139.99      0.01%

Lea                0.00     -60.79    -228.19    -228.19       0.00       0.00      0.00%

Leah             415.18     -67.20    -398.98      16.20       3.00     415.18      0.01%

Lesley             0.00     -10.00     -89.99     -89.99       0.00       0.00      0.00%

Lily               0.00      -8.00     -71.99     -71.99       0.00       0.00      0.00%

Linda              0.00     -14.00    -125.99    -125.99       0.00       0.00      0.00%

Louise            95.99      -9.00    -355.97    -259.98       0.33      32.00      0.00%

Louise             0.00     -28.00    -111.99    -111.99       0.00       0.00      0.00%

Loustos            0.00     -12.00    -107.99    -107.99       0.00       0.00      0.00%

Margaret         161.99       0.00    -161.99       0.00       1.00     161.99      0.00%

Margaux           83.99     -56.00     -83.99       0.00       1.00      83.99      0.00%

Maria        441,049.27 101,387.66 -35,488.04 405,561.23       1.66     167.00     13.29%

Maria             63.99       4.00     -47.99      16.00       1.00      63.99      0.00%

Maria Eduard       0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Marilyn          160.99     -13.00    -157.99       3.00       1.50      80.50      0.00%

Marina             0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Mark           1,384.88     187.00  -1,047.92     336.96       1.75     173.11      0.04%

Marta            269.99     109.98       0.00     269.99       3.00     269.99      0.01%

Martha Lucia   1,613.29     146.10    -281.48   1,331.81       1.44     179.25      0.05%

Matias        23,130.87   4,779.01  -1,327.87  21,803.00       1.56     136.87      0.70%

Meg                0.00     -13.00    -116.99    -116.99       0.00       0.00      0.00%

Merrilyn     120,163.06  19,516.73  -7,570.47 112,592.59       1.49     155.65      3.62%

Michael            0.00     -10.00     -89.99     -89.99       0.00       0.00      0.00%

Miryana          135.99      34.00       0.00     135.99       1.00     135.99      0.00%

Mobina           251.48      12.50    -173.99      77.49       1.50     125.74      0.01%

Nenci            424.98     -26.99    -817.96    -392.98       0.57      60.71      0.01%

Nenci              0.00     -37.00    -332.99    -332.99       0.00       0.00      0.00%

Nguyen Mai A       0.00     -40.99     -89.00     -89.00       0.00       0.00      0.00%

Nicole            39.20     -50.19    -208.99    -169.79       0.33      13.07      0.00%

Nikki              0.00     -49.75    -149.25    -149.25       0.00       0.00      0.00%

Pamela           897.47    -249.30  -2,023.62  -1,126.15       0.33      99.72      0.03%

Pammi        182,375.21  35,249.46 -12,309.30 170,065.91       1.60     168.09      5.49%

Paul              99.99     100.00       0.00      99.99       1.00      99.99      0.00%

Paula        369,605.51  68,789.40 -20,502.28 349,103.23       1.60     180.38     11.13%

Pilar          2,375.13     318.93    -498.20   1,876.93       1.25     148.45      0.07%

Rabeya             0.00     -13.00    -116.99    -116.99       0.00       0.00      0.00%

Rabina         3,249.78     706.94    -797.96   2,451.82       1.46     116.06      0.10%

Raquel         2,630.18     142.31  -1,110.16   1,520.02       1.21     109.59      0.08%

Renee        599,842.87 137,123.27 -39,668.23 560,174.64       1.68     170.94     18.07%

Renne             89.99       0.00     -89.99       0.00       1.00      89.99      0.00%

Rhonda           772.48      76.97    -609.46     163.02       1.40     154.50      0.02%

Rimma            845.14    -116.20  -1,538.90    -693.76       0.70      84.51      0.03%

Ruchika            0.00     -40.00    -159.99    -159.99       0.00       0.00      0.00%

Saakshi           90.30       0.00     -90.30       0.00       1.00      90.30      0.00%

Sally            359.99      -8.00    -431.98     -71.99       0.50     180.00      0.01%

Sandra           134.99       0.00    -134.99       0.00       1.00     134.99      0.00%

Sara          20,634.21   3,634.50  -1,908.36  18,725.85       1.53     139.42      0.62%

Sarah          2,416.88     292.98       0.00   2,416.88       3.50     604.22      0.07%

Sarah         75,490.86  17,559.65  -5,785.76  69,705.10       1.58     185.03      2.27%

Saraya           126.19      22.80    -139.99     -13.80       2.00     126.19      0.00%

Shabair      310,456.73  57,998.99 -17,615.12 292,841.61       1.68     186.01      9.35%

Shanley            0.00     -35.00    -314.99    -314.99       0.00       0.00      0.00%

Shann            279.19      29.80    -159.99     119.20       2.00     279.19      0.01%

Shirley            0.00     -27.00     -62.99     -62.99       0.00       0.00      0.00%

Shonnah           63.20       6.80     -80.99     -17.79       1.00      63.20      0.00%

Sofia          1,252.74     223.40     -79.20   1,173.54       1.11     139.19      0.04%

Sophia             0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Store            720.37     -10.39  -1,451.93    -731.56       0.58      60.03      0.02%

Susan              0.00      -9.00     -80.99     -80.99       0.00       0.00      0.00%

Susan         38,878.88   8,400.57  -2,407.46  36,471.42       1.60     190.58      1.17%

Susan            103.99     -26.00    -103.99       0.00       1.00     103.99      0.00%

Susan            597.98      59.98       0.00     597.98       1.50     149.50      0.02%

Susanne            0.00     -15.00    -134.99    -134.99       0.00       0.00      0.00%

Susie             80.99       0.00     -80.99       0.00       1.00      80.99      0.00%

Tania              0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Tania              0.00     -70.99     -99.00     -99.00       0.00       0.00      0.00%

Tara               0.00     -75.00    -224.98    -224.98       0.00       0.00      0.00%

Tate          33,381.38   7,402.21  -2,256.21  31,125.17       1.74     171.19      1.01%

Taznin             0.00     -26.00    -103.99    -103.99       0.00       0.00      0.00%

Teresa       415,018.33  95,771.59 -24,986.88 390,031.45       1.63     166.07     12.50%

Tina               0.00     -55.00    -294.98    -294.98       0.00       0.00      0.00%

Tracey        27,901.65   7,633.29  -1,632.38  26,269.27       1.65     156.75      0.84%

Valeria            0.00       0.00    -189.00    -189.00       0.00       0.00      0.00%

Victoria       2,407.32     904.42     -74.99   2,332.33       1.93     160.49      0.07%

Wendy Ann     18,843.52   3,883.40    -829.43  18,014.09       1.45     138.56      0.57%

Yifan            127.49     -42.50    -127.49       0.00       1.00     127.49      0.00%

Zoe                0.00      -9.00     -80.99     -80.99       0.00       0.00      0.00%

_________________________________________________________________________________________

Total       3,319,620.7 697,760.35-245,878.093,073,742.6       1.63     172.50    100.00%

_________________________________________________________________________________________

Printed by Maria

At Store SC FS Balmain

9/02/2025 4:41 PM        POSREPS.SalesPerformance44251
"""

In [ ]:
clean_data = [cd for cd in data.split("\n") if cd]
print(len(clean_data))
for cd in clean_data:
    print(cd)

In [ ]:
timestamp = " ".join(clean_data[-1].split()[:-1])
print(f"timestamp = {timestamp}")

store = " ".join(clean_data[-2].split()[2:])
brand = store.split()[0]
store_type = store.split()[1]
location = " ".join(store.split()[2:])
print(f"store = {store}\nbrand = {brand}\nstore type = {store_type}\nlocation = {location}")

user = " ".join(clean_data[-3].split()[2:])
print(f"user = {user}")

In [ ]:
sales_data = [sale.split() for sale in clean_data if sale.endswith("%")]
total = sales_data.pop()

for sd in sales_data:
    if len(sd) > 8:
        # name = " ".join(sd[:-7])
        # new_sd = [name] + sd[-7:]
        # index = sales_data.index(sd)
        # sales_data[index] = new_sd

        sales_data[sales_data.index(sd)] = [" ".join(sd[:-7])] + sd[-7:]

In [ ]:
row_headers = clean_data[5:7]
for i in row_headers:
    print(i)

# Too messy, do this manually.
column_headers = ["Sales Person", "Retail $ Incl Disc", "Discount", "Returns", "Net $", "Avg Sale Units", "Avg Sale $", "% Store Total"]

In [ ]:
import pandas as pd
df = pd.DataFrame(sales_data, columns = column_headers)

# df["Retail $ Incl Disc"] = df["Retail $ Incl Disc"].str.replace(",", "").astype(float)
# df["Discount"] = df["Discount"].str.replace(",", "").astype(float)
# df["Returns"] = df["Returns"].str.replace(",", "").astype(float)
# df["Net $"] = df["Net $"].str.replace(",", "").astype(float)
# df["Avg Sale Units"] = df["Avg Sale Units"].str.replace(",", "").astype(float)
# df["Avg Sale $"] = df["Avg Sale $"].str.replace(",", "").astype(float)

columns_to_clean = ["Retail $ Incl Disc", "Discount", "Returns", "Net $", "Avg Sale Units", "Avg Sale $"]
df[columns_to_clean] = df[columns_to_clean].replace(",", "", regex=True).astype(float)

df["% Store Total"] = df["% Store Total"].str.rstrip("%").astype(float)
print(df)

In [ ]:
df.to_csv(f"{store} {timestamp}.csv", index=False)

In [ ]:
timestamp = """9/02/2025 4:41 PM"""
timestamp = timestamp.replace("/", "_")
timestamp = timestamp.replace(":", "_")
print(timestamp)

In [1]:
store_data = """
                            SALES PERFORMANCE REPORT

                                 Including GST

                        Avg and % calculated on Retail $

 

_________________________________________________________________________________________

Sales Person   Retail $   Discount    Returns      Net $   Avg Sale   Avg Sale    % Store

              Incl Disc                                       Units          $      Total

_________________________________________________________________________________________

Alejandra        134.99       0.00    -134.99       0.00       1.00     134.99      0.00%

Alice            231.98     -50.00    -381.97    -149.99       0.67      77.33      0.01%

Amal             381.97     -26.00    -237.98     143.99       1.50     190.99      0.01%

Amanda        57,239.91  10,199.23  -3,265.24  53,974.67       1.67     173.98      1.72%

Amy              143.99    -102.00    -297.98    -153.99       0.50      72.00      0.00%

Amy               95.98     -24.00     -95.98       0.00       2.00      95.98      0.00%

Andy             399.97      39.00       0.00     399.97       1.33     133.32      0.01%

Angela             0.00     -48.00    -111.99    -111.99       0.00       0.00      0.00%

Anita              0.00     -17.00    -152.99    -152.99       0.00       0.00      0.00%

Anna             129.00     -25.00    -224.99     -95.99       1.00     129.00      0.00%

Anthony        3,495.94     300.90     -54.00   3,441.94       1.25     174.80      0.11%

Avishka       19,354.29   5,200.20  -1,034.73  18,319.56       1.35     154.83      0.58%

Bansi          2,635.81     506.99    -332.98   2,302.83       1.43     188.27      0.08%

Barbara       69,056.24  17,139.75  -6,263.99  62,792.25       1.57     168.84      2.08%

Barclay          152.99       4.00    -116.99      36.00       1.00     152.99      0.00%

Bronte           859.93     160.00       0.00     859.93       2.00     214.98      0.03%

Carla            295.99       0.00    -295.99       0.00       1.00     295.99      0.01%

Carol             62.99      27.00       0.00      62.99       1.00      62.99      0.00%

Catherine      5,723.64     562.93  -1,277.92   4,445.72       1.52     197.37      0.17%

Charlotte          0.00       0.00     -99.00     -99.00       0.00       0.00      0.00%

Christian        451.95     -86.00    -587.94    -135.99       1.25     112.99      0.01%

Christian      8,926.77   3,025.29    -917.90   8,008.87       1.73     162.30      0.27%

Christine        313.48    -155.00  -1,632.41  -1,318.93       0.18      28.50      0.01%

Cindy             71.99     -63.00    -476.98    -404.99       0.50      36.00      0.00%

Cindy            528.46    -265.50  -2,432.84  -1,904.38       0.36      37.75      0.02%

Clair            791.92     228.00       0.00     791.92       8.00     791.92      0.02%

Claire           143.99       0.00    -143.99       0.00       1.00     143.99      0.00%

DAVID JONES      188.19      30.80    -159.99      28.20       2.00     188.19      0.01%

David          5,211.69     838.94    -305.97   4,905.72       1.56     193.03      0.16%

Daya             195.49      51.49    -146.99      48.50       1.50      97.75      0.01%

Debbie             0.00     -50.99     -99.00     -99.00       0.00       0.00      0.00%

Dhanushree       395.97       9.20    -214.19     181.78       3.00     395.97      0.01%

Diana          3,170.93     661.99    -692.17   2,478.76       1.45     158.55      0.10%

Dolly          1,129.92      76.00       0.00   1,129.92       6.00     564.96      0.03%

Elena              0.00       0.00    -129.99    -129.99       0.00       0.00      0.00%

Emanuele      19,489.46   3,944.80  -1,331.89  18,157.57       1.67     158.45      0.59%

Emily          3,313.23     321.50     -89.99   3,223.24       1.80     220.88      0.10%

Erika              0.00       0.00    -149.00    -149.00       0.00       0.00      0.00%

Farnaz           323.96       0.00    -323.96       0.00       4.00     323.96      0.01%

Fatemeh        4,740.65   1,019.00       0.00   4,740.65       1.46     197.53      0.14%

Florencia          0.00       0.00     -49.00     -49.00       0.00       0.00      0.00%

Francesca     45,504.31   8,773.16  -3,656.77  41,847.54       1.76     207.78      1.37%

Gabrielle      1,671.89     356.98       0.00   1,671.89       1.40     167.19      0.05%

Gail             259.99      19.00    -278.99     -19.00       2.00     259.99      0.01%

Gearldine          0.00     -60.50    -284.50    -284.50       0.00       0.00      0.00%

Georgia      149,964.25  29,098.32  -8,426.03 141,538.22       1.72     187.93      4.52%

Gina             159.00     -14.01    -203.99     -44.99       0.50      79.50      0.00%

Giovanna         369.97     -16.00    -423.96     -53.99       0.75      92.49      0.01%

Grace              0.00       0.00     -79.00     -79.00       0.00       0.00      0.00%

Haniya             0.00     -29.80    -119.20    -119.20       0.00       0.00      0.00%

India          7,070.03   1,703.27     -71.99   6,998.04       1.63     130.93      0.21%

Ingrid            59.99       0.00     -59.99       0.00       1.00      59.99      0.00%

Isabel Dias       89.99       0.00     -89.99       0.00       1.00      89.99      0.00%

Jacqueline       116.99       0.00    -116.99       0.00       1.00     116.99      0.00%

Jennifer         178.99    -230.80    -987.14    -808.15       0.25      22.37      0.01%

Jessica            0.00     -19.80     -79.20     -79.20       0.00       0.00      0.00%

Jessie        59,650.25  11,849.76  -2,494.88  57,155.37       1.64     212.28      1.80%

Jill (Jilly) 141,761.53  32,536.08  -9,254.16 132,507.37       1.70     203.68      4.27%

Jiyaa              0.00     -30.00    -119.99    -119.99       0.00       0.00      0.00%

Julie            451.45     -67.00    -592.45    -141.00       1.20      90.29      0.01%

Kandy              0.00     -52.00    -207.98    -207.98       0.00       0.00      0.00%

Katerina         193.48    -150.68    -479.27    -285.79       0.40      38.70      0.01%

Kelly             97.99    -152.00    -467.96    -369.97       0.33      32.66      0.00%

Kiara              0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Klara            360.97     -64.00    -360.97       0.00       1.00     120.32      0.01%

Lana               0.00    -129.50    -770.45    -770.45       0.00       0.00      0.00%

Lara             279.98       0.00    -279.98       0.00       1.00     139.99      0.01%

Lea                0.00     -60.79    -228.19    -228.19       0.00       0.00      0.00%

Leah             415.18     -67.20    -398.98      16.20       3.00     415.18      0.01%

Lesley             0.00     -10.00     -89.99     -89.99       0.00       0.00      0.00%

Lily               0.00      -8.00     -71.99     -71.99       0.00       0.00      0.00%

Linda              0.00     -14.00    -125.99    -125.99       0.00       0.00      0.00%

Louise            95.99      -9.00    -355.97    -259.98       0.33      32.00      0.00%

Louise             0.00     -28.00    -111.99    -111.99       0.00       0.00      0.00%

Loustos            0.00     -12.00    -107.99    -107.99       0.00       0.00      0.00%

Margaret         161.99       0.00    -161.99       0.00       1.00     161.99      0.00%

Margaux           83.99     -56.00     -83.99       0.00       1.00      83.99      0.00%

Maria        441,049.27 101,387.66 -35,488.04 405,561.23       1.66     167.00     13.29%

Maria             63.99       4.00     -47.99      16.00       1.00      63.99      0.00%

Maria Eduard       0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Marilyn          160.99     -13.00    -157.99       3.00       1.50      80.50      0.00%

Marina             0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Mark           1,384.88     187.00  -1,047.92     336.96       1.75     173.11      0.04%

Marta            269.99     109.98       0.00     269.99       3.00     269.99      0.01%

Martha Lucia   1,613.29     146.10    -281.48   1,331.81       1.44     179.25      0.05%

Matias        23,130.87   4,779.01  -1,327.87  21,803.00       1.56     136.87      0.70%

Meg                0.00     -13.00    -116.99    -116.99       0.00       0.00      0.00%

Merrilyn     120,163.06  19,516.73  -7,570.47 112,592.59       1.49     155.65      3.62%

Michael            0.00     -10.00     -89.99     -89.99       0.00       0.00      0.00%

Miryana          135.99      34.00       0.00     135.99       1.00     135.99      0.00%

Mobina           251.48      12.50    -173.99      77.49       1.50     125.74      0.01%

Nenci            424.98     -26.99    -817.96    -392.98       0.57      60.71      0.01%

Nenci              0.00     -37.00    -332.99    -332.99       0.00       0.00      0.00%

Nguyen Mai A       0.00     -40.99     -89.00     -89.00       0.00       0.00      0.00%

Nicole            39.20     -50.19    -208.99    -169.79       0.33      13.07      0.00%

Nikki              0.00     -49.75    -149.25    -149.25       0.00       0.00      0.00%

Pamela           897.47    -249.30  -2,023.62  -1,126.15       0.33      99.72      0.03%

Pammi        182,375.21  35,249.46 -12,309.30 170,065.91       1.60     168.09      5.49%

Paul              99.99     100.00       0.00      99.99       1.00      99.99      0.00%

Paula        369,605.51  68,789.40 -20,502.28 349,103.23       1.60     180.38     11.13%

Pilar          2,375.13     318.93    -498.20   1,876.93       1.25     148.45      0.07%

Rabeya             0.00     -13.00    -116.99    -116.99       0.00       0.00      0.00%

Rabina         3,249.78     706.94    -797.96   2,451.82       1.46     116.06      0.10%

Raquel         2,630.18     142.31  -1,110.16   1,520.02       1.21     109.59      0.08%

Renee        599,842.87 137,123.27 -39,668.23 560,174.64       1.68     170.94     18.07%

Renne             89.99       0.00     -89.99       0.00       1.00      89.99      0.00%

Rhonda           772.48      76.97    -609.46     163.02       1.40     154.50      0.02%

Rimma            845.14    -116.20  -1,538.90    -693.76       0.70      84.51      0.03%

Ruchika            0.00     -40.00    -159.99    -159.99       0.00       0.00      0.00%

Saakshi           90.30       0.00     -90.30       0.00       1.00      90.30      0.00%

Sally            359.99      -8.00    -431.98     -71.99       0.50     180.00      0.01%

Sandra           134.99       0.00    -134.99       0.00       1.00     134.99      0.00%

Sara          20,634.21   3,634.50  -1,908.36  18,725.85       1.53     139.42      0.62%

Sarah          2,416.88     292.98       0.00   2,416.88       3.50     604.22      0.07%

Sarah         75,490.86  17,559.65  -5,785.76  69,705.10       1.58     185.03      2.27%

Saraya           126.19      22.80    -139.99     -13.80       2.00     126.19      0.00%

Shabair      310,456.73  57,998.99 -17,615.12 292,841.61       1.68     186.01      9.35%

Shanley            0.00     -35.00    -314.99    -314.99       0.00       0.00      0.00%

Shann            279.19      29.80    -159.99     119.20       2.00     279.19      0.01%

Shirley            0.00     -27.00     -62.99     -62.99       0.00       0.00      0.00%

Shonnah           63.20       6.80     -80.99     -17.79       1.00      63.20      0.00%

Sofia          1,252.74     223.40     -79.20   1,173.54       1.11     139.19      0.04%

Sophia             0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Store            720.37     -10.39  -1,451.93    -731.56       0.58      60.03      0.02%

Susan              0.00      -9.00     -80.99     -80.99       0.00       0.00      0.00%

Susan         38,878.88   8,400.57  -2,407.46  36,471.42       1.60     190.58      1.17%

Susan            103.99     -26.00    -103.99       0.00       1.00     103.99      0.00%

Susan            597.98      59.98       0.00     597.98       1.50     149.50      0.02%

Susanne            0.00     -15.00    -134.99    -134.99       0.00       0.00      0.00%

Susie             80.99       0.00     -80.99       0.00       1.00      80.99      0.00%

Tania              0.00     -34.00    -135.99    -135.99       0.00       0.00      0.00%

Tania              0.00     -70.99     -99.00     -99.00       0.00       0.00      0.00%

Tara               0.00     -75.00    -224.98    -224.98       0.00       0.00      0.00%

Tate          33,381.38   7,402.21  -2,256.21  31,125.17       1.74     171.19      1.01%

Taznin             0.00     -26.00    -103.99    -103.99       0.00       0.00      0.00%

Teresa       415,018.33  95,771.59 -24,986.88 390,031.45       1.63     166.07     12.50%

Tina               0.00     -55.00    -294.98    -294.98       0.00       0.00      0.00%

Tracey        27,901.65   7,633.29  -1,632.38  26,269.27       1.65     156.75      0.84%

Valeria            0.00       0.00    -189.00    -189.00       0.00       0.00      0.00%

Victoria       2,407.32     904.42     -74.99   2,332.33       1.93     160.49      0.07%

Wendy Ann     18,843.52   3,883.40    -829.43  18,014.09       1.45     138.56      0.57%

Yifan            127.49     -42.50    -127.49       0.00       1.00     127.49      0.00%

Zoe                0.00      -9.00     -80.99     -80.99       0.00       0.00      0.00%

_________________________________________________________________________________________

Total       3,319,620.7 697,760.35-245,878.093,073,742.6       1.63     172.50    100.00%

_________________________________________________________________________________________

Printed by Maria

At Store SC FS Balmain

9/02/2025 4:41 PM        POSREPS.SalesPerformance44251
"""

In [ ]:
# data = data given in via text input

import os
import pandas as pd

def store_sales_data(store_data):
    clean_data = [cd for cd in store_data.split("\n") if cd]
    
    timestamp = " ".join(clean_data[-1].split()[:-1])
    timestamp = timestamp.replace("/", "_")
    timestamp = timestamp.replace(":", "_")
    store = " ".join(clean_data[-2].split()[2:])
    
    sales_data = [sale.split() for sale in clean_data if sale.endswith("%")]
    total = sales_data.pop()

    for sd in sales_data:
        if len(sd) > 8:
            sales_data[sales_data.index(sd)] = [" ".join(sd[:-7])] + sd[-7:]
    
    column_headers = ["Sales Person", "Retail $ Incl Disc", "Discount", "Returns", "Net $", "Avg Sale Units", "Avg Sale $", "% Store Total"]
    df = pd.DataFrame(sales_data, columns = column_headers)
    
    columns_to_clean = ["Retail $ Incl Disc", "Discount", "Returns", "Net $", "Avg Sale Units", "Avg Sale $"]
    df[columns_to_clean] = df[columns_to_clean].replace(",", "", regex=True).astype(float)
    df["% Store Total"] = df["% Store Total"].str.rstrip("%").astype(float)
    
    df.to_csv(f"{store} {timestamp}.csv", index=False)
    return df

In [3]:
df = store_sales_data(store_data)

In [4]:
import pandasql as psql

def df_process(df, sql_query):
    result = psql.sqldf(sql_query, locals())
    return result

In [5]:
sql_queries = """SELECT * FROM df;
SELECT * FROM df WHERE Discount > 10;
SELECT SUM("Retail $ Incl Disc") AS Total_Retail FROM df;
SELECT AVG("Net $") AS Average_Net_Sales FROM df;
SELECT "Sales Person", SUM("Retail $ Incl Disc") AS Total_Sales FROM df GROUP BY "Sales Person";
SELECT * FROM df ORDER BY "Avg Sale $" DESC;
SELECT "Sales Person", SUM(Returns) AS Total_Returns FROM df GROUP BY "Sales Person" ORDER BY Total_Returns DESC LIMIT 3;
SELECT * FROM df WHERE "Avg Sale Units" > 5 AND Discount < 15;
SELECT "Sales Person", AVG(Discount) AS Average_Discount FROM df GROUP BY "Sales Person";"""

# SQL Queries suggested by ChatGPT

### 1. **Select all rows from the DataFrame:**

```sql
SELECT * FROM df;
```

### 2. **Filter rows where the discount is greater than a specific value:**

```sql
SELECT * FROM df WHERE Discount > 10;
```

This will return all rows where the `Discount` column is greater than 10.

### 3. **Calculate the total retail amount (`Retail $ Incl Disc`) for all sales:**

```sql
SELECT SUM("Retail $ Incl Disc") AS Total_Retail FROM df;
```

This will return the sum of all values in the `Retail $ Incl Disc` column.

### 4. **Find the average net sales (`Net $`):**

```sql
SELECT AVG("Net $") AS Average_Net_Sales FROM df;
```

This will return the average of the `Net $` column.

### 5. **Group data by "Sales Person" and calculate the total sales (`Retail $ Incl Disc`) for each person:**

```sql
SELECT "Sales Person", SUM("Retail $ Incl Disc") AS Total_Sales FROM df GROUP BY "Sales Person";
```

This will return a list of salespeople with the total sales value for each person.

### 6. **Order the data by "Avg Sale $" in descending order:**

```sql
SELECT * FROM df ORDER BY "Avg Sale $" DESC;
```

This will return all rows sorted by `Avg Sale $` in descending order.

### 7. **Find the top 3 salespeople with the highest total returns:**

```sql
SELECT "Sales Person", SUM(Returns) AS Total_Returns
FROM df
GROUP BY "Sales Person"
ORDER BY Total_Returns DESC
LIMIT 3;
```

This will return the top 3 salespeople with the highest total returns.

### 8. **Filter rows where the "Avg Sale Units" is greater than a specific value and "Discount" is less than another value:**

```sql
SELECT * FROM df WHERE "Avg Sale Units" > 5 AND Discount < 15;
```

This will return rows where the `Avg Sale Units` is greater than 5 and the `Discount` is less than 15.

### 9. **Find the average discount given per salesperson:**

```sql
SELECT "Sales Person", AVG(Discount) AS Average_Discount FROM df GROUP BY "Sales Person";
```

This will return the average discount each salesperson has applied.

In [6]:
sql_query = sql_queries.split("\n")
results = []
for sq in sql_query:
    results.append(df_process(df, sq))

In [7]:
r0_all_rows = results[0]
r1_disc_greater_than = results[1]
r2_tot_retail_amt = results[2]
r3_avg_net_sales = results[3]
r4_grp_salesP_tot_sales_for_ea = results[4]
r5_avg_sale_desc_ord = results[5]
r6_top_3_returns = results[6]
r7_avg_sale_disc_filters = results[7]
r8_avg_disc_per_saleP = results[8]